In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import numpy as np
import pandas as pd

%matplotlib inline
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
%config InlineBackend.figure_format = 'svg'

from pylab import rcParams
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12,5)

In [6]:
data = pd.read_csv(r'C:\Users\Gleb\Desktop\transactions_last_2.csv', sep=';', nrows=5000000)
data

,purchdate,amount,mcc,mrchcity,mrchname,cnum
0,2019-11-02 00:00:00,9000000.0,5691,MOSCOW,IA7D1H Z1D1T7,MJNLMQ
1,2019-11-02 00:00:00,9000000.0,5691,MOSCOW,IA7D1H Z1D1T7,MJNLMQ
2,2019-10-25 00:00:00,7716900.0,5691,MOSCOW,HXL4K TL4EEXD,ELETCO
3,2019-11-29 00:00:00,5100000.0,6513,SANKT-PETERBU,7X 1E7HXD H1DKW1IKCL,EL0KSF
4,2019-12-03 00:00:00,5023956.6,5944,MOSKVA,73 7HJXK7 (W7X),MPKIJJ
...,...,...,...,...,...,...
4999995,2019-12-14 00:00:00,9566.0,5511,MOSCOW,C4E4DX,KRMRML
4999996,2019-09-18 00:00:00,9566.0,3011,MOSKVA,71JX9HXE W7X,8ELHG4
4999997,2019-10-06 00:00:00,9566.0,5941,SANKT-PETERBU,KWXJEC7KE1J K29,ASGXCH
4999998,2019-11-25 00:00:00,9566.0,5691,MILKOVO,U4H801JJ41K BB,EEUU70
4999999,2019-10-18 00:00:00,9566.0,5541,MARKOVA,KEX 94HEJ-B,E44TPG

### Распределение mcc на датасете

In [7]:
print(data.shape)
data.mcc.value_counts()

(5000000, 6)

6011    2226399
6012    1231145
6538     314194
5691      80527
5411      78022
         ...
3653          1
3722          1
3730          1
3741          1
7217          1
Name: mcc, Length: 370, dtype: int64

### Предобработка + объединение датасетов

In [9]:
stores = pd.read_csv(r'C:\Users\Gleb\Desktop\store_last_2.csv', sep=';', encoding='windows-1251')
stores = stores.rename(columns={"merchant_name": "mrchname"})

df = data[data['mcc']==6012]
# df = df.loc[df['mcc'] == 6011]
df.mcc = df.mcc.astype('object')
df = df.reset_index(drop=True)

merge_data = pd.merge(df, stores, on='mrchname', how='inner')
merge_data = merge_data.sort_values(by='purchdate', ascending=True)
merge_data = merge_data.reset_index(drop=True)
# merge_data = merge_data.drop(['Unnamed: 0'], axis=1)

KeyError: "['Unnamed: 0'] not found in axis"

### Удаляем выбросы и выбираем магазин-клиент в качестве таргета

In [12]:
merge_data.amount.describe()

count    1.538140e+06
mean     4.424369e+04
std      5.111444e+04
min      9.594190e+03
25%      1.460000e+04
50%      2.500000e+04
75%      5.000000e+04
max      5.000000e+05
Name: amount, dtype: float64

In [19]:
merge_data = merge_data.loc[merge_data['amount'] < merge_data.amount.quantile(0.95)]
# merge_data = merge_data.loc[merge_data['amount'] > 20.00]
merge_data.shape

(1406968, 7)

In [26]:
# merge_data.loc[merge_data['store_name'] == 'ашан рязанка', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан рублевка', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан сокольники', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан кунцево', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан рублевка', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан гагаринский', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан сокольники', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан кунцево', 'store_name'] = 'ашан'
# merge_data.loc[merge_data['store_name'] == 'ашан гагаринский ', 'store_name'] = 'ашан'

# merge_data.loc[merge_data['store_name'] == 'глобус красногорск', 'store_name'] = 'глобус'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1017', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1356', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1014', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1073', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1019', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1061', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1077', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1048', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1050', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1318', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1322', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1011', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1049', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1012', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1018', 'store_name'] = 'metro cash&carry'
# merge_data.loc[merge_data['store_name'] == 'метро стор 1049', 'store_name'] = 'metro cash&carry'

# merge_data.loc[merge_data['store_name'] == 'ав экспресс меню', 'store_name'] = 'азбука вкуса'
# merge_data.loc[merge_data['store_name'] == 'азбука вкуса daily', 'store_name'] = 'азбука вкуса'

In [34]:
merge_data.store_name.str.replace('айфф', 'Райффайзенбанк')

0                              Мамина-Сибиряка, 101
1                                          Банкомат
2                                               ВТБ
3                              Мамина-Сибиряка, 101
4                                          Банкомат
                             ...
1538135    Банкомат РРайффайзенбанкайзенбанк  43731
1538136    Банкомат РРайффайзенбанкайзенбанк  46171
1538137    Банкомат РРайффайзенбанкайзенбанк  43731
1538138    Банкомат РРайффайзенбанкайзенбанк  33651
1538139    Банкомат РРайффайзенбанкайзенбанк  47721
Name: store_name, Length: 1406968, dtype: object

In [32]:
# merge_data[merge_data['store_name'].str.contains('айф')].store_name.value_counts()

merge_data.store_name.value_counts()

Газпромбанк C2C                  47998
Банкомат Уралсиб                 22106
Банкомат                         21864
ВТБ                              19755
Росбанк                           8998
                                 ...
ТЦ Ривьера                           1
Сбербанк                             1
Mercury                              1
Банкомат Райффайзенбанк 45571        1
Boss House                           1
Name: store_name, Length: 1965, dtype: int64

In [33]:
merge_data.head()

,purchdate,amount,mcc,mrchcity,mrchname,cnum,store_name
0,2019-09-17 00:00:00,10000.0,6011,YEkaterinburg,"C.K404JO737, MVM",LLNLMP,"Мамина-Сибиряка, 101"
1,2019-09-17 00:00:00,25500.0,6011,MOSCOW,7ECVP5V 7H3XD,E46D6V,Банкомат
2,2019-09-17 00:00:00,100000.0,6011,MOSKVA G,T0B5,EL60F1,ВТБ
3,2019-09-17 00:00:00,100000.0,6011,YEkaterinburg,"C.K404JO737, MVM",EEQUSA,"Мамина-Сибиряка, 101"
4,2019-09-17 00:00:00,12000.0,6011,KHimki,"SO C43JXJ7OXD,",ELD8JT,Банкомат

In [30]:
array1 = merge_data.store_name.value_counts().index.tolist()
array2 = merge_data.store_name.value_counts().tolist()
array3 = []
for i, j in zip(array1, array2):
    couple = i + ' ' + str(j)
    array3.append(couple)
array3

['Пятерочка 1173115',
 'Перекресток 977340',
 'Вкусвилл 712524',
 'Азбука Вкуса 457181',
 'Магнит 344221',
 'Магнолия 237137',
 'Дикси 212835',
 'Мясновъ 161927',
 'SPAR 139304',
 'Мираторг 124378',
 'Ашан 124240',
 'Fix Price 82901',
 'Окей 70796',
 'Metro Cash&Carry 56695',
 'Лента 48762',
 'Глобус Красногорск 43635',
 'Глобус 37021',
 'Виктория 35695',
 'Атак 33401',
 'Ярче! 30747',
 'Ашан Гагаринский 30736',
 'Продукты 26506',
 'Ашан Сокольники 25672',
 'Ашан Кунцево 20172',
 'Да! 19386',
 'Карусель 18650',
 'Добрынинский 18518',
 'Авоська 16178',
 'Ашан Рязанка 15417',
 'Ашан Рублевка 14756',
 'Азбука вкуса 12910',
 'Продуктовый Магазин 11022',
 'Eurospar 10505',
 'Гастроном 10366',
 'Метро Стор 1017 10246',
 'Густо 10238',
 'Алые Паруса 9271',
 'Метро Стор 1356 9213',
 'Супермаркет Сити 9133',
 'IKEA 8958',
 'Вивомаркет 8945',
 'Верный 8776',
 'Метро Стор 1014 8765',
 'Адмирал 8048',
 'Фасоль 7991',
 'Метро Стор 1073 7529',
 'Метро Стор 1019 7314',
 'Фреш Маркет 7054',
 'Утконос 7051',
 'Победа Вкуса 7004',
 'Spar 6709',
 'Полярная Звезда Супермаркет 5969',
 'Метро Стор 1061 5758',
 'Бахетле 5708',
 'Близнецы Универсам 5679',
 'Гастроном Бим 4633',
 'Метро Стор 1077 4605',
 'Daily Food 4401',
 'Метро Стор 1048 4162',
 'Рыбная мануфактура 4005',
 'Метро Стор 1050 3965',
 'Универсам 3716',
 'Ремит 3608',
 'Отдохни 3586',
 'Метро Стор 1318 3305',
 'Магазин 3281',
 'Супермаркет Бахетле 3218',
 'Минимаркет 3008',
 'Solomka 2908',
 'Универсам76 2801',
 'Доброном 2498',
 'Елисеевский 2351',
 'Гурмэ Времена Года 2283',
 'Мега центр италия 2246',
 'Фреш 2211',
 'Макси 2141',
 'Метро Стор 1322 2097',
 'Milli 2076',
 'Iqos 1890',
 'Interstyle 1830',
 'Гурмэ ЦУМ 1688',
 'Айко 1621',
 'Кронекс 1564',
 'Мосхозторг 1546',
 'Мясницкий ряд 1485',
 'Гурмаркет 1458',
 'Caramell 1408',
 'Лавка кофе чая 1406',
 'Супермаркет Трамплин 1309',
 'Сити киоск 1268',
 'Трц олимп 1184',
 'Labirint.Ru 1151',
 'Gusto 1126',
 'Ммгрупстрой 1122',
 'Вита сервис 1113',
 'Супермаркет Алые Паруса 1108',
 'Мандарин-маркет 1097',
 'Гурман 1077',
 'Воробей маркет 1042',
 'Фреш Маркет Кафе 1029',
 'Азбука Вкуса Daily 1021',
 'Славяна 1011',
 'Хлебник 996',
 'Близнецы универсам 960',
 'Релком 952',
 'Гурмэ Гименей 938',
 'Великий 928',
 'Поляна 926',
 'Продуктовый Магазин 24 904',
 'Сеть Гастрономов Бим 892',
 'Тц столичный 889',
 'Народный кондитер 874',
 'Супермаркет Да 854',
 'Домаркет 784',
 'Витамины 781',
 'Куулклевер 766',
 'Азия 751',
 'Стиль. семья 743',
 'Метро Стор 1011 734',
 'Bon Appetit 725',
 'Фермач 702',
 'Банкомат 653',
 'Apelsin 651',
 'Супермаркет 7-12 650',
 'Деловая Русь 642',
 'Гурмания 641',
 'Ав экспресс меню 605',
 'Деликатеска.Ру 562',
 'Заморская Лавка 561',
 'Старый город 556',
 'Булочная 554',
 'Супермаркет Арка 512',
 'Город-сад 504',
 'Бирмаркет 484',
 'Fix price 483',
 'Каспий Плюс 481',
 'Швейный мир 477',
 'Greengo 475',
 'Огород 473',
 'Цветной Маркет 457',
 'Правда Кофе 447',
 'Ovechka market 430',
 'Фианит ломбард 399',
 'Белорусский Фермер Смт 398',
 'Аптека 387',
 'Мясорубка мясо тут 382',
 'Винлаб 372',
 'Хохловка 366',
 'Круассан 364',
 'Находка 361',
 'Белорусские Продукты 354',
 'Кошер Гурмэ 347',
 'Империал 345',
 'Адмирал маркет 340',
 'Штофмаркет 315',
 'Складсизо.рф 310',
 'Shaker bar 307',
 'Браво Плюс 307',
 'Мясная Лавка 288',
 'Кулинария 288',
 'Winemafia 272',
 'Магия вкуса 271',
 'Organik Market 270',
 'Владимирский Стандарт 249',
 'Хмелёфф 242',
 'Megasport 223',
 'Colabeans 220',
 'Фортуна 215',
 'Кантата 207',
 'Белорусские Колбасы 201',
 'Рублевский 198',
 'Claret 195',
 'Хозмакс 192',
 'Nuts&berries 181',
 'Хц Лейпциг 169',
 'Метро Стор 1049 163',
 'Максимус Груп 161',
 'Bonape 156',
 'Морозко 150',
 'Метро Стор 1012 143',
 'Цветы 141',
 'Мичурино молоко 137',
 'Молочные Продукты 130',
 'Мясной стандарт 129',
 'Тамбовский Дворик 125',
 'Farfetch 120',
 'Розовый Слон 118',
 'Чайбург 114',
 'Молочный дворик 107',
 'Лакомка 96',
 'Глобус Гурмэ 89',
 'Вкусняшка 88',
 'Метро Стор 1018 81',
 'Аметист 78',
 'Le Bon Gout 77',
 'Igooods 76',
 'Славянка 62',
 'Окраина 61',
 'Московский Метрополитен 61',
 'Simple Wine 56',
 'Планета zoo 53',
 'Шантимэль 52',
 'Мясо халяль 49',
 'Mlesna 49',
 'Магазин солнышко 47',
 'Смешные цены 46',
 'Ферма На Дом 45',
 'Молоканские овощи 31',
 'Овощи И Фрукты 24',
 'Эко Маркет 22',
 'Профессор пуф 21',
 'Магазин Свежее Мясо 20',
 'Ника 19',
 'Мята Lounge 18',
 'Naturliche 15',
 'Сырная Лавка 14',
 'Зоомагазин 12',
 'Салон Цветов 11',
 'Юниор 11',
 'Кофе с собой 8',
 'Суши Wok 7',
 'Дворик 6',
 'Фермерский Парк 6',
 'Винотека 5',
 'Колобок пекарня 2',
 'Военторг 2',
 'Payu 1',
 'Мосметро 1',
 'Оптовичок 1',
 'Виктория  1',
 'Рыбсеть 1']